// Generated by gencpp from file ultra_sonics/proximity_reading.msg
// DO NOT EDIT!


#ifndef ULTRA_SONICS_MESSAGE_PROXIMITY_READING_H
#define ULTRA_SONICS_MESSAGE_PROXIMITY_READING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ultra_sonics
{
template <class ContainerAllocator>
struct proximity_reading_
{
  typedef proximity_reading_<ContainerAllocator> Type;

  proximity_reading_()
    : x(0)
    , y(0)
    , z(0)
    , distance(0.0)
    , accuracy(0.0)  {
    }
  proximity_reading_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , z(0)
    , distance(0.0)
    , accuracy(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;

   typedef int16_t _z_type;
  _z_type z;

   typedef float _distance_type;
  _distance_type distance;

   typedef float _accuracy_type;
  _accuracy_type accuracy;




  typedef boost::shared_ptr< ::ultra_sonics::proximity_reading_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ultra_sonics::proximity_reading_<ContainerAllocator> const> ConstPtr;

}; // struct proximity_reading_

typedef ::ultra_sonics::proximity_reading_<std::allocator<void> > proximity_reading;

typedef boost::shared_ptr< ::ultra_sonics::proximity_reading > proximity_readingPtr;
typedef boost::shared_ptr< ::ultra_sonics::proximity_reading const> proximity_readingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ultra_sonics::proximity_reading_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ultra_sonics::proximity_reading_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ultra_sonics

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ultra_sonics': ['/home/parallels/Desktop/catkin_ws/src/drivers/ultra_sonics/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ultra_sonics::proximity_reading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ultra_sonics::proximity_reading_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ultra_sonics::proximity_reading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ultra_sonics::proximity_reading_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ultra_sonics::proximity_reading_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ultra_sonics::proximity_reading_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ultra_sonics::proximity_reading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9c7353d28dec7d7c97f9d50d19e40b5";
  }

  static const char* value(const ::ultra_sonics::proximity_reading_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9c7353d28dec7d7ULL;
  static const uint64_t static_value2 = 0xc97f9d50d19e40b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ultra_sonics::proximity_reading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ultra_sonics/proximity_reading";
  }

  static const char* value(const ::ultra_sonics::proximity_reading_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ultra_sonics::proximity_reading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x\n\
int16 y\n\
int16 z\n\
float32 distance\n\
float32 accuracy\n\
";
  }

  static const char* value(const ::ultra_sonics::proximity_reading_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ultra_sonics::proximity_reading_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.distance);
      stream.next(m.accuracy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct proximity_reading_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ultra_sonics::proximity_reading_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ultra_sonics::proximity_reading_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int16_t>::stream(s, indent + "  ", v.z);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "accuracy: ";
    Printer<float>::stream(s, indent + "  ", v.accuracy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ULTRA_SONICS_MESSAGE_PROXIMITY_READING_H
